version: "3"
services:
    similarity-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5001:5001
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
