# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: similarity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10similarity.proto\x12\nsimilarity\"1\n\x0e\x41\x64\x64ItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"2\n\x0f\x41\x64\x64ItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x12SearchItemsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"(\n\x13SearchItemsResponse\x12\x11\n\tsearch_id\x18\x01 \x01(\t\",\n\x17GetSearchResultsRequest\x12\x11\n\tsearch_id\x18\x01 \x01(\t\"E\n\x18GetSearchResultsResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.similarity.SearchResult\"/\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\x92\x02\n\x17SimilaritySearchService\x12\x44\n\x07\x41\x64\x64Item\x12\x1a.similarity.AddItemRequest\x1a\x1b.similarity.AddItemResponse\"\x00\x12P\n\x0bSearchItems\x12\x1e.similarity.SearchItemsRequest\x1a\x1f.similarity.SearchItemsResponse\"\x00\x12_\n\x10GetSearchResults\x12#.similarity.GetSearchResultsRequest\x1a$.similarity.GetSearchResultsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'similarity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals['_ADDITEMREQUEST']._serialized_start = 32
    _globals['_ADDITEMREQUEST']._serialized_end = 81
    _globals['_ADDITEMRESPONSE']._serialized_start = 83
    _globals['_ADDITEMRESPONSE']._serialized_end = 133
    _globals['_SEARCHITEMSREQUEST']._serialized_start = 135
    _globals['_SEARCHITEMSREQUEST']._serialized_end = 170
    _globals['_SEARCHITEMSRESPONSE']._serialized_start = 172
    _globals['_SEARCHITEMSRESPONSE']._serialized_end = 212
    _globals['_GETSEARCHRESULTSREQUEST']._serialized_start = 214
    _globals['_GETSEARCHRESULTSREQUEST']._serialized_end = 258
    _globals['_GETSEARCHRESULTSRESPONSE']._serialized_start = 260
    _globals['_GETSEARCHRESULTSRESPONSE']._serialized_end = 329
    _globals['_SEARCHRESULT']._serialized_start = 331
    _globals['_SEARCHRESULT']._serialized_end = 378
    _globals['_SIMILARITYSEARCHSERVICE']._serialized_start = 381
    _globals['_SIMILARITYSEARCHSERVICE']._serialized_end = 655
# @@protoc_insertion_point(module_scope)
